<?php
/**
 * PERFICIENT INDIA PVT LTD.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://shop.perficient.com/license-community.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento COMMUNITY edition
 * =================================================================
 * Perficient does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Perficient does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * PHP version 5.x
 *
 * @category  Perficient
 * @package   Perficient_GoogleTagManager
 * @author    Perficient <mukesh.soni@perficient.com>
 * @copyright 2016 PERFICIENT INDIA PVT LTD
 * @license   OSL http://shop.perficient.com/license-community.txt
 * @version   GIT:0.0.2.1
 * @link      http://shop.perficient.com/extensions/google-tag-manager-by-perficient
 */
$helper = Mage::helper('perficient_googletagmanager');
if ($helper->isEnabled()) {
    ?>
    <!-- Google Tag Manager -->
    <?php
    echo $this->_getDataLayer();
    $containerId = $helper->getContainerId();
    $dataLayerName = $helper->getDataLayerName();
    $isSecure = Mage::app()->getFrontController()->getRequest()->isSecure();
    ?>
    <noscript>
    <iframe src="<?php echo ($isSecure) ? 'https://' : 'http://'; ?>www.googletagmanager.com/ns.html?id=<?php echo $containerId; ?>"
            height=\"0\" width=\"0\" style=\"display:none;visibility:hidden\">
    </iframe>
    </noscript>
    <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='<?php echo $dataLayerName; ?>'?'&l='+l:'';j.async=true;j.src=
                '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','<?php echo $dataLayerName; ?>','<?php echo $containerId; ?>');        
    </script>
    <!-- End Google Tag Manager -->
<?php } ?>