<?php echo $this->getChildHtml('order_info2');?>
<?php echo $this->getChildHtml('custom.order');?>


<?php /* ?>

<?php $order = $this->getOrder() ?>

<div class="entry-edit box-left">
    <div class="entry-edit-head">
        <h4 class="icon-head">My Custom YYY</h4>
    </div>
    <fieldset>
        <div id="customextra_custom_block">
            Special message
        </div>
    </fieldset>
</div>
<div class="clear"></div>

<?php */ ?>
